### ISSUE TITLE
/etc/nanorc is not recognized

### ISSUE THREAD

**Issue by charraeus** [jdel/syno-packages#6]
Hi,
I've installed the nano community package. When starting nano it does not find the existing _/etc/nanorc_ file which I want to use system-wide for all users.

A _.nanorc_ file in the userhome is found and works well.

So maybe the systemwide _nanorc_ has to be put in another directory?

**Comment by jdel** [comment]
Hello, 

Have you tried nano from the synocommunity repository ?
Mine is very outdated and I have no plans in updating it in the future.

**Comment by charraeus** [comment]
Hello Julien,
Yes, I‘ve installed it from the synocommunity repository. 
Is there another contact person resp. maintainer if you are not the one?

Best regards,
Christian 

Von meinem Händi gesendet

**Comment by jdel** [comment]
Hi Christian,

Yes, please install the `nano` package from SynoCommunity (as opposed to `gnu-nano` in my repository here). If it doesn't work as expected, please raise an issue on [SynoCommunity repo](https://github.com/SynoCommunity/spksrc)
