### ISSUE TITLE
USB Serial Drivers Kernel Problem

### ISSUE THREAD

**Issue by dossidr** [jdel/syno-packages#7]
Hello JDEL,

on the apollolake arch is not possible to be load Kernel Modules.
DS918+

dmesg Failure:

[  155.515266] usbserial: USB Serial support registered for FTDI USB Serial Device
[  155.570797] usbserial: version magic '4.4.59 SMP preempt mod_unload ' should be '4.4.59+ SMP preempt mod_unload '

Can you help me to be fix this issue?

Best regards

Denny

**Comment by jdel** [comment]
Hello Denny, 

These packages are not supported anymore. Please seek help directly with the maintainer of the package you have installed.

Best of luck,
Julien
